### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by carpodaster** [Absolventa/absolventa.github.io#8]

**Comment by axlwaii** [comment]
I like the default Absolventa logo and think there is no need for creating an extra one for our blog.
However a gave your idea with the matrix code style overlay a shot :)

![logo-blog](https://cloud.githubusercontent.com/assets/524320/8520039/48e35d8a-23d7-11e5-85c4-0f396bb5f9a2.jpg)

**Comment by dansch** [comment]
Markus gave a proper answer - let's keep the current logo. It's beautiful. The best logo we've ever had. It's true.
